cat("Hello there!")
cat("We are the people of Planet Earth and number around 7 billion.")
cat("Our planet is the only planet in our solar system.")
cat("Through our pursuit of knowledge, we have implored to discover other forms of intelligent life.")
cat("We have sent out messages over the years, the one of which being "Across the Universe" by the Beatles.")
cat("Did you hear it?")
cat("They were the best band of their time and remain one of the most popular today.")
cat("We have recieved one signal, the Wow! signal, but do not know where it came from?")
cat("Was it you?")
cat("We would love to talk to you!")